In [2]:
# to install numpy in your system 
! pip3 install numpy

Defaulting to user installation because normal site-packages is not writeable


In [ ]:
#import numpy using alias
import numpy as np

In [6]:
# making numpy array using array function
x = np.array([2,3,4,4,5,6,7,3])
print(x)

[2 3 4 4 5 6 7 3]


In [8]:
#every element will become floating point number because of one float number
x1 = np.array([2,3,4,4,5,6,7,3.1])
print(x1)

[2.  3.  4.  4.  5.  6.  7.  3.1]


In [ ]:
print(type(x1))# type of numpy array

<class 'numpy.ndarray'>


In [ ]:
x2 = [1,2,3,3,4]
print(type(x2))# it will print list class

<class 'list'>


In [11]:
# making numpy array using tuple
x3 = np.array((1,2,3,3,4,3,2))
print(x3)
print(type(x3))

[1 2 3 3 4 3 2]
<class 'numpy.ndarray'>


In [ ]:
a = np.arange(0,4,1)# making numpy array using arange()
print(a)

[0 1 2 3]


In [15]:
a = np.arange(-10,-4,1)# making numpy array using arange()
print(a)

[-10  -9  -8  -7  -6  -5]


In [16]:
a = np.arange(10,-4,-20)# making numpy array using arange()
print(a)

[10]


In [25]:
a1 = np.random.random((3))#randomly generates number to make an array automatically
a1

array([0.50823284, 0.08183614, 0.07135385])

In [ ]:
x1 = np.random.randint(50,size=6)#one dimentional array
print(x1)
print()
x2 = np.random.randint(10,size =(3,3))# 2D array
print(x2)
print()
x3 = np.random.randint(10,size =(3,3,2))# 3D array
print(x3)
print()

[ 9 19  2  3 46 19]

[[6 7 4]
 [6 3 4]
 [5 9 8]]

[[[9 0]
  [9 5]
  [4 2]]

 [[1 0]
  [1 4]
  [7 2]]

 [[6 9]
  [0 6]
  [4 0]]]



In [ ]:
# an array containing single element is called 0 dimentional array
x = np.array(23)
print(x)# it is also called scaler vector

23


In [ ]:

print("dimention ",x.ndim)#prints dimention of the array, using ndim attribute

dimention  0


In [44]:
arr= np.random.randint(50,size=(1,2,3,4))
print(arr)
print(arr.ndim,"dimentions")

[[[[ 7 10 34 45]
   [36 43  4 33]
   [12 30 40 24]]

  [[ 6 16 31 26]
   [ 9 43 13 33]
   [ 8 25 48 44]]]]
4 dimentions


In [1]:
import numpy as np

In [3]:
arr1 = np.arange(10)
print(arr1)
arr2 = np.arange(12).reshape(3,4)
print(arr2)
arr3 = np.arange(24).reshape(2,4,3)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [ ]:
arr1[::-1]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [9]:
arr2[0,:]

array([0, 1, 2, 3])

In [8]:
arr2[:,0]


array([0, 4, 8])

In [10]:
arr2[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [11]:
arr2[::2,:2:]

array([[0, 1],
       [8, 9]])

In [12]:
arr2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [16]:
arr2[-1::-2,-1::-3]

array([[11,  8],
       [ 3,  0]])

In [24]:
arr2[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [26]:
arr3[1,1::2,::2]

array([[15, 17],
       [21, 23]])

In [28]:
print(arr3[0],end='\n\n')
print(arr3[0,0],end='\n\n')
print(arr3[1,:3],end='\n\n')
print(arr3[0,:2,::2])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[0 1 2]

[[12 13 14]
 [15 16 17]
 [18 19 20]]

[[0 2]
 [3 5]]


Numpy Array Attirbutes
-a numpy array has several attributes that indicates the element type,element size, shapeof array, size of arrays, etc.
-We can 


In [29]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([11,2.2,3.3,4.4])

print(a1.dtype)
print(a2.dtype)

int64
float64


In [30]:
print(a1.itemsize)
print(a2.itemsize)

8
8


In [31]:
print(a1.nbytes)
print(a2.nbytes)

40
32


In [32]:
a1 = np.array([1,2,3,4])
a2 = np.array([[1,2,3,4,5],[6,7,8,0,9]])

print(a1.ndim)
print(a2.ndim)

print(a1.shape)
print(a2.shape)

print(a1.size)
print(a2.size)

1
2
(4,)
(2, 5)
4
10


In [34]:
print(np.zeros(10))
print()
print(np.zeros((3,6)))
print()
print(np.zeros((2,3,2)))
print()

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]



In [38]:
print(np.ones(10,dtype='int'))
print()
print(np.ones((3,6),dtype='int'))
print()
print(np.ones((2,3,2),dtype='int'))
print()

[1 1 1 1 1 1 1 1 1 1]

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]



In [40]:
np.identity(2)#default data as float 


array([[1., 0.],
       [0., 1.]])

In [41]:
a1 = np.array([1,3,5,7])
b1 = np.array([2,4,6,8])

print(a1)
print(b1)

[1 3 5 7]
[2 4 6 8]


1. Scaler operation


In [42]:
#all scalar operations on 1D array using operators
print(a1+5)
print(a1-5)
print(a1*2)
print(a1/2)
print(a1//2)
print(-a1)
print(a1**2)
print(a1%2)

[ 6  8 10 12]
[-4 -2  0  2]
[ 2  6 10 14]
[0.5 1.5 2.5 3.5]
[0 1 2 3]
[-1 -3 -5 -7]
[ 1  9 25 49]
[1 1 1 1]


Dot product


In [4]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([2,5,7])
np.dot(arr1,arr2)

np.int64(33)

In [5]:
x = np.arange(50).reshape(10,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [6]:
np.mean(x)

np.float64(24.5)

In [ ]:
np.mean(x,axis=0)# mean of individual columns

array([22.5, 23.5, 24.5, 25.5, 26.5])

In [ ]:
np.mean(x,axis=1)#mean of individual rows

array([ 2.,  7., 12., 17., 22., 27., 32., 37., 42., 47.])

In [10]:
y = np.arange(20).reshape(4,5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
np.max(y)

np.int64(19)

In [12]:
np.min(x)

np.int64(0)

In [13]:
np.max(x)

np.int64(49)

In [14]:
np.min(x,axis=0)

array([0, 1, 2, 3, 4])

In [15]:
np.min(x,axis=1)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [16]:
np.var(x)

np.float64(208.25)

In [17]:
np.var(x,axis=0)

array([206.25, 206.25, 206.25, 206.25, 206.25])

In [18]:
np.var(x,axis=1)

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [19]:
np.sum(x)

np.int64(1225)

In [20]:
np.sum(x,axis=0)

array([225, 235, 245, 255, 265])

In [21]:
np.sum(x,axis=1)

array([ 10,  35,  60,  85, 110, 135, 160, 185, 210, 235])

In [23]:
p25 = np.percentile(x,25)
p50 = np.percentile(x,50)
p75 = np.percentile(x,75)
p100 = np.percentile(x,100)

In [24]:
print("25th percentile",p25)
print("50th percentile",p50)
print("75th percentile",p75)
print("100th percentile",p100)

25th percentile 12.25
50th percentile 24.5
75th percentile 36.75
100th percentile 49.0


In [25]:
a1 = np.array([2,3,4,1,4,2,5,5,7,8,6,9])
for i in a1:
    print(i,end = " ")

2 3 4 1 4 2 5 5 7 8 6 9 

In [26]:
a1 = np.array([2,3,4,1,4,2,5,5,7,8,6,9])
for i in a1:
    if i%2==0:
        print(i,end = " ")

2 4 4 2 8 6 

In [29]:
a2 = np.arange(20).reshape(4,5)
for i in a2:
    print(i,end="\n\n")

[0 1 2 3 4]

[5 6 7 8 9]

[10 11 12 13 14]

[15 16 17 18 19]



stacking of numpy array

In [30]:
s1 = np.arange(12).reshape(4,3)
s2 = np.arange(12,24).reshape(4,3)

In [31]:
s1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
s2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [ ]:
s3 = np.hstack((s1,s2))# horizontal stack
s3

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17],
       [ 6,  7,  8, 18, 19, 20],
       [ 9, 10, 11, 21, 22, 23]])

In [ ]:
s4 = np.vstack((s1,s2))# vertical stack
s4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

spliting of numpy array 

In [37]:
a1 = np.hsplit(s3,2)
a1

[array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]])]

In [40]:
a2 = np.hsplit(s3,3)
a2

[array([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10]]),
 array([[ 2, 12],
        [ 5, 15],
        [ 8, 18],
        [11, 21]]),
 array([[13, 14],
        [16, 17],
        [19, 20],
        [22, 23]])]

In [44]:
a3 = np.vsplit(s3,4)
a3

[array([[ 0,  1,  2, 12, 13, 14]]),
 array([[ 3,  4,  5, 15, 16, 17]]),
 array([[ 6,  7,  8, 18, 19, 20]]),
 array([[ 9, 10, 11, 21, 22, 23]])]